### ISSUE TITLE
Encode `Bytes` values as protobufs `bytes` instead of `string`.

### ISSUE THREAD

**Issue by aherrmann** [mirage/mirage-lambda#20]
[`Bytes`](https://github.com/mirage/mirage-lambda/blob/master/proto/lambda.proto#L106) are encoded as `string`, instead of `bytes`. Protobufs `string` [restricts to UTF-8](https://developers.google.com/protocol-buffers/docs/proto#scalar) while `bytes` allows arbitrary bytes. It seems like `Bytes` should be encoded using protobufs `bytes`.

**Comment by dinosaure** [comment]
Close by #26
