### ISSUE TITLE
Required primitives

### ISSUE THREAD

**Issue by aherrmann** [mirage/mirage-lambda#22]
- [x] Block device information
    `Block.get_info` together with `read_write`, `sector_size`, `size_sectors` seems sufficient.
- [x] Reading/writing blocks
    `Block.read`, and `Block.write` seem sufficient.
- [x] Error handling
    - `Block.error`, and `Block.write_error` are abstract and cannot be serialized.
        Primitives to render them to strings to be able to return the error message to the client would be useful.
    - `Block.pp_error`, and `Block.pp_write_error` take a `Formatter.formatter` which is abstract and cannot be created in a MirageLambda program.
        These functions return unit, so they are not useful for error reporting to the client. They might be useful for server-side logging?
- [x] Buffers/bytes conversion
    Could the primitives `Cstruct.to_string`, `Cstruct.of_string`, `Cstruct.blit`, `Cstruct.blit_to_string`, `Cstruct.blit_from_string` be replaced by their `bytes` counter-parts?
    Strings serialize to the protobufs `string` type which is restricted to UTF-8.
    Bytes should serialize (see #20) to the protobufs `bytes` type which is unrestricted.
- [x] Computing on buffers/bytes
    Currently there is no way to perform computation on bytes (e.g. calculate a check-sum).
    Primitives like `byte_to_int` and `int_to_byte` (or similar) and bit operations like left/right shift should make most operations possible.
    This point probably needs some more discussion.
- [x] Converting between integer types
    MirageLambda currently has `int`, `int32`, `int64`. Arithmetic operators only works on `int`. Some operations (like `sector_size`, or `Block.read/write` operate on `int64`). Conversions between these would be useful.

**Comment by dinosaure** [comment]
I think, all tasks are completed (specially with #26). If I miss something, tell me 👍 !
