### ISSUE TITLE
Block-device IO in recursive functions

### ISSUE THREAD

**Issue by aherrmann** [mirage/mirage-lambda#29]
In Mirage-Lambda recursive functions are encoded as functions that return `Either a b`, where `Left` stands for "another iteration" and `Right` stands for "terminate". Primitives for block-device IO have return types of shape `Lwt a`. There are no primitives to convert `Lwt a` to `a`.

This makes it impossible to perform - and depend on the output of - block-device IO in the body of a recursive function, as such a function could at best return `Lwt (Either a b)`.

**Comment by dinosaure** [comment]
I think it's done with #32 

With my binary:
```
# (fun (is:(Cstruct.t list), os:(Cstruct.t list)) -> rec fact (x:(int * int)) : int Lwt.t = let acc : int = fst x in let v : int = snd x in if v = 0 then return (R (int * int) acc) else return (L (acc * v, v - 1) int) in let fact (x:int) : int Lwt.t = fact (1, x) in fact 5):int Lwt.t
>>> receive: 120.
```

**Comment by dinosaure** [comment]
Could you test it 😃 ?

**Comment by aherrmann** [comment]
@dinosaure Tested, looks like it's working. Thanks!

I'm wondering, is `Brc` required, or is it just meant as a short-cut?

Assuming the following works with `Brc`
```
Brc someLwtEither
  (Return (foo B))
  (Return (bar B))
```
Couldn't the same thing be achieved with `>>=` (i.e. `bind`) and `Swt`?
```
someLwtEither >>= \someEither ->
  Swt someEither
    (Return (foo B))
    (Return (bar B))
```
